import datetime
from typing import Set

from entity.availability import Availability
from entity.city import City
from entity.court import Court
from entity.division import Division
from entity.player import Player
from entity.team import Team
from interactor.matchmaking.matchmaking import MatchmakingImpl

input_data = [{'team_id': 'rec0PkRLRqX17ERGT',
               'player1_id': 'recd1EtfW4z1abmmZ',
               'player2_id': 'recfwFg1Bb6fOSjEf',
               'player1_coords': ('35.715806', '-78.711512'),
               'player2_coords': ('35.582594', '-78.750939'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': set(),
               'evening': {'Saturday 8/26'}},
              {'team_id': 'rec1mbKQy77e68Tg6',
               'player1_id': 'rec9xjegu77NKg0GF',
               'player2_id': 'reczYQB5oD8mwvqin',
               'player1_coords': ('35.779886', '-78.741256'),
               'player2_coords': ('35.779886', '-78.741256'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court B',
               'morning': {'Saturday 8/26'},
               'afternoon': {'Saturday 8/26'},
               'evening': {'Monday 8/21',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Tuesday 8/22'}},
              {'team_id': 'rec2ar2dfnMOI6Aiw',
               'player1_id': 'recyPzvQsGWAkjvIn',
               'player2_id': 'rece7IjOqxWu8bIpU',
               'player1_coords': ('35.81478', '-78.616182'),
               'player2_coords': ('35.790455', '-78.629036'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Tuesday 8/22'}},
              {'team_id': 'rec2n1ibiVePjSng4',
               'player1_id': 'recU04BxXmqqyOGpB',
               'player2_id': 'recv2b7NeuYkhTN1B',
               'player1_coords': ('35.657487', '-78.36167'),
               'player2_coords': ('35.796575', '-78.648423'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Friday 8/25', 'Monday 8/21', 'Tuesday 8/22'}},
              {'team_id': 'rec2tzA3gDISzZQBi',
               'player1_id': 'recgFUP6i9kuPT64d',
               'player2_id': 'rechcxOAJEBYbJKiD',
               'player1_coords': ('35.7529617', '-78.7785972'),
               'player2_coords': ('35.818444', '-78.698893'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21', 'Tuesday 8/22'}},
              {'team_id': 'rec5ARIiLKQ6exC7S',
               'player1_id': 'recd3EU4urI7YMLX8',
               'player2_id': 'rechm8wg4YaNCW68p',
               'player1_coords': ('33.846877', '-84.331816'),
               'player2_coords': ('33.846877', '-84.331816'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21', 'Tuesday 8/22'}},
              {'team_id': 'rec8GwTNWUDQB3sO9',
               'player1_id': 'recQwMy7Ru3aEpNXk',
               'player2_id': 'recvvLqNIls2xhvDG',
               'player1_coords': ('35.697894', '-78.626576'),
               'player2_coords': ('35.771552', '-78.617692'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'recBRjEfm7uhIDTaQ',
               'player1_id': 'recyh9HewribzJoeA',
               'player2_id': 'recjj4Rew3d5DEaGe',
               'player1_coords': ('34.015921', '-84.302848'),
               'player2_coords': ('33.921268', '-84.6965382'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'recBnQLQ2Oq6oFBUT',
               'player1_id': 'recBXFEPiYmNoptcP',
               'player2_id': 'recgKnFVvI0YyDKs9',
               'player1_coords': ('33.822131', '-84.352769'),
               'player2_coords': ('33.7450085', '-84.3587676'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21'}},
              {'team_id': 'recCQJByA6yZs9eh5',
               'player1_id': 'recWb8QG4KizopYlA',
               'player2_id': 'recY7leBD7vTA5zVY',
               'player1_coords': ('33.919538', '-84.674077'),
               'player2_coords': ('33.912473', '-84.557181'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21', 'Tuesday 8/22'}},
              {'team_id': 'recCw5HLo5X4IDvut',
               'player1_id': 'recPM5tiFCu7Ikse2',
               'player2_id': 'recshTc5Rqa31z8BQ',
               'player1_coords': ('33.826563', '-84.352301'),
               'player2_coords': ('33.826563', '-84.352301'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21'}},
              {'team_id': 'recDPlm6NU2bOuf2F',
               'player1_id': 'rec3YzO00Ow9tA219',
               'player2_id': 'recnIqnqX5tKHJbfd',
               'player1_coords': ('35.853862', '-78.634557'),
               'player2_coords': ('35.853862', '-78.634557'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21',
                           'Saturday 8/26',
                           'Thursday 8/24',
                           'Wednesday 8/23'}},
              {'team_id': 'recEI71iB8laEEKns',
               'player1_id': 'reck3ATFgAOgdeNw7',
               'player2_id': 'recmWk7eaPGUiRqYY',
               'player1_coords': ('35.8064145', '-78.6570751'),
               'player2_coords': ('35.661734', '-78.710224'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court C',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25', 'Saturday 8/26', 'Sunday 8/27'}},
              {'team_id': 'recEesFZjkzfc9rOV',
               'player1_id': 'recix55BOuXappl0u',
               'player2_id': 'recqH3vIWpO4aq21T',
               'player1_coords': ('35.8989439', '-78.6670659'),
               'player2_coords': ('35.898951', '-78.662197'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Sunday 8/27'},
               'evening': {'Monday 8/21', 'Sunday 8/27', 'Thursday 8/24'}},
              {'team_id': 'recEfGAtvc0zarWdL',
               'player1_id': 'rec7PDstLtszBKocQ',
               'player2_id': 'recMkJIOScw3lzlhv',
               'player1_coords': ('35.674185', '-78.666783'),
               'player2_coords': ('35.6598759', '-78.6736644'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court C',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25', 'Monday 8/21', 'Wednesday 8/23'}},
              {'team_id': 'recG1xO6UVnOSLXDx',
               'player1_id': 'rec2hisf0QHb13kHS',
               'player2_id': 'rec4YK3gDipeZRZgt',
               'player1_coords': ('35.859903', '-78.678836'),
               'player2_coords': ('35.739165', '-78.911223'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25', 'Monday 8/21', 'Wednesday 8/23'}},
              {'team_id': 'recH2JFbQM6QnoSUY',
               'player1_id': 'recF9PaDmIRSSsc5f',
               'player2_id': 'recRF89kMtAtTfHHl',
               'player1_coords': ('33.7541543', '-84.3013687'),
               'player2_coords': ('33.800223', '-84.524932'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court C',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recJtVmTx2urRhpIz',
               'player1_id': 'recJG1H7LcehD6PVH',
               'player2_id': 'recP4jH0zYebL9cKF',
               'player1_coords': ('35.848278', '-78.667376'),
               'player2_coords': ('35.928019', '-78.624721'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recK0aLTPLZW8X6rA',
               'player1_id': 'recoZMn9GL5z2RErM',
               'player2_id': 'recvv2GkPEW6R5yDu',
               'player1_coords': ('35.752811', '-78.775956'),
               'player2_coords': ('35.752811', '-78.775956'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court C',
               'morning': {'Friday 8/25', 'Tuesday 8/22', 'Wednesday 8/23'},
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recL0Veh3rQ9MDs0a',
               'player1_id': 'recFkEYfauyuPdD9e',
               'player2_id': 'recLSCMU92IzzGP9K',
               'player1_coords': ('35.787937', '-78.648423'),
               'player2_coords': ('35.787937', '-78.648423'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Friday 8/25', 'Tuesday 8/22', 'Wednesday 8/23'},
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recM5J6NIXwUhRGGi',
               'player1_id': 'recA25c8NfpPxXZeV',
               'player2_id': 'recx3xWpIYqWb1suS',
               'player1_coords': ('33.88361', '-84.527137'),
               'player2_coords': ('33.883644', '-84.527154'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': set(),
               'evening': {'Saturday 8/26', 'Tuesday 8/22'}},
              {'team_id': 'recM5w8fxf4bUvf2f',
               'player1_id': 'rec04GSmkObqLn52c',
               'player2_id': 'recvhn77owsJGJdpY',
               'player1_coords': ('35.872791', '-78.523941'),
               'player2_coords': ('35.858092', '-78.531336'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21', 'Tuesday 8/22', 'Wednesday 8/23'}},
              {'team_id': 'recMkLC7MFUEp7JFQ',
               'player1_id': 'rec3Iz8CT6i750XRR',
               'player2_id': 'rec6zOVb47tRM2ziA',
               'player1_coords': ('33.806237', '-84.364888'),
               'player2_coords': ('33.806237', '-84.364888'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Monday 8/21'},
               'afternoon': {'Monday 8/21'},
               'evening': {'Monday 8/21', 'Tuesday 8/22', 'Wednesday 8/23'}},
              {'team_id': 'recMsmMTQBk3CGsHq',
               'player1_id': 'recgWpgXsjL00z1va',
               'player2_id': 'recj0xgTpoqKaIUI0',
               'player1_coords': ('33.80332', '-84.346321'),
               'player2_coords': ('33.788511', '-84.359158'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Friday 8/25', 'Monday 8/21', 'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recNP0tMJplzNgYrc',
               'player1_id': 'rec2LVjXeQuLS9umE',
               'player2_id': 'recOwmUSjr8Jjeq2O',
               'player1_coords': ('35.764558', '-78.464776'),
               'player2_coords': ('35.764558', '-78.464776'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court A',
               'morning': {'Monday 8/21', 'Tuesday 8/22', 'Wednesday 8/23'},
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recNmobHlY1gIWygX',
               'player1_id': 'recbq1zDFWtMWsMsr',
               'player2_id': 'recM46y2Vo41O796e',
               'player1_coords': ('35.891764', '-78.708993'),
               'player2_coords': ('35.866835', '-78.615334'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Thursday 8/24', 'Tuesday 8/22'}},
              {'team_id': 'recOU88kRb355gooo',
               'player1_id': 'rec5jekwBhN24AmZk',
               'player2_id': 'recorULrQelxaXuT5',
               'player1_coords': ('33.78143', '-84.377537'),
               'player2_coords': ('33.78143', '-84.377537'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Wednesday 8/23'}},
              {'team_id': 'recPWpqy7QV268Y8y',
               'player1_id': 'rec0Gyr0yOV89hzdX',
               'player2_id': 'recG1VjPtNyjxVUWO',
               'player1_coords': ('35.803015', '-78.639588'),
               'player2_coords': ('35.767455', '-78.640737'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court C',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25', 'Sunday 8/27', 'Tuesday 8/22'}},
              {'team_id': 'recShhwOsiehdNrbL',
               'player1_id': 'rec3QJUfPXM4gHGmh',
               'player2_id': 'recHjNPWJqLChIT2h',
               'player1_coords': ('33.775168', '-84.377962'),
               'player2_coords': ('33.763388', '-84.364874'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court C',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25', 'Sunday 8/27', 'Tuesday 8/22'}},
              {'team_id': 'recTQsnu6v9JBojkX',
               'player1_id': 'recDMlIdcs6MUWLz2',
               'player2_id': 'recPDlw1Stp0roDMF',
               'player1_coords': ('33.992834', '-84.345799'),
               'player2_coords': ('34.147859', '-84.4682003'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court B',
               'morning': {'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Saturday 8/26', 'Sunday 8/27'}},
              {'team_id': 'recVz789gjr0cBOJP',
               'player1_id': 'recFcgAmRmaDAzAcH',
               'player2_id': 'recUs43779knqaGhA',
               'player1_coords': ('35.867417', '-78.590217'),
               'player2_coords': ('35.7815451', '-78.5082952'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Tuesday 8/22'}},
              {'team_id': 'recWNHYH9h3JqDqBV',
               'player1_id': 'recPZA3wTXUvYZdVR',
               'player2_id': 'recvgF7joHAx7126c',
               'player1_coords': ('33.83785', '-84.338345'),
               'player2_coords': ('33.796479', '-84.416502'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Friday 8/25',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'recXybatiJIXQ3jjS',
               'player1_id': 'recpHm8GnGfb3TWHE',
               'player2_id': 'recShQy9VMvOwHXdR',
               'player1_coords': ('35.911759', '-78.744042'),
               'player2_coords': ('35.835356', '-78.637536'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Friday 8/25', 'Wednesday 8/23'}},
              {'team_id': 'recaCeqvwLySAcFvW',
               'player1_id': 'recfpwuHO81QAwHLN',
               'player2_id': 'reclqs3MqoOMD4TwS',
               'player1_coords': ('33.749866', '-84.369013'),
               'player2_coords': ('33.750674', '-84.348381'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Saturday 8/26', 'Sunday 8/27', 'Thursday 8/24'}},
              {'team_id': 'recadVbzfYXd0fNiq',
               'player1_id': 'recxFtNy11Z9WUOZh',
               'player2_id': 'rec2TqiJUsVozyulN',
               'player1_coords': ('33.924351', '-84.312367'),
               'player2_coords': ('33.786284', '-84.382853'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court B',
               'morning': {'Friday 8/25',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'},
               'afternoon': {'Friday 8/25',
                             'Saturday 8/26',
                             'Sunday 8/27',
                             'Thursday 8/24',
                             'Tuesday 8/22',
                             'Wednesday 8/23'},
               'evening': set()},
              {'team_id': 'recbAcURU87uC651u',
               'player1_id': 'recWPMptwKP4IRdJC',
               'player2_id': 'reco5eaNqVfukQ95O',
               'player1_coords': ('35.777824', '-78.645607'),
               'player2_coords': ('35.777824', '-78.645607'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25',
                           'Monday 8/21',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Wednesday 8/23'}},
              {'team_id': 'recbDiNOcZDze8zqX',
               'player1_id': 'recI1CkkoYIHeMjm3',
               'player2_id': 'recUDwCozUePEXlqt',
               'player1_coords': ('33.876727', '-84.328472'),
               'player2_coords': ('33.7754295', '-84.2811601'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Tuesday 8/22', 'Wednesday 8/23'}},
              {'team_id': 'recbspAjbhOhzUShl',
               'player1_id': 'rec3EhmqARtJqSeNJ',
               'player2_id': 'recSzn5NdETcUXbVP',
               'player1_coords': ('33.792818', '-84.388369'),
               'player2_coords': ('33.792818', '-84.388369'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25',
                           'Monday 8/21',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'reccFODMQ6niVKTip',
               'player1_id': 'rec5TCX3jmvgcUQgw',
               'player2_id': 'recpIyR5D8SAfLvoZ',
               'player1_coords': ('35.956837', '-78.719918'),
               'player2_coords': ('35.956837', '-78.719918'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court A',
               'morning': {'Friday 8/25', 'Thursday 8/24', 'Wednesday 8/23'},
               'afternoon': {'Wednesday 8/23'},
               'evening': {'Friday 8/25', 'Thursday 8/24', 'Wednesday 8/23'}},
              {'team_id': 'recdK7jeRmyabIwwk',
               'player1_id': 'rece6MANAJ9U3H8b6',
               'player2_id': 'recq1KK5oLDSE5Mna',
               'player1_coords': ('35.9278358', '-78.5253107'),
               'player2_coords': ('35.936419', '-78.610434'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court B',
               'morning': {'Sunday 8/27'},
               'afternoon': set(),
               'evening': {'Monday 8/21', 'Tuesday 8/22'}},
              {'team_id': 'recdjAU1SK0F08LVT',
               'player1_id': 'recBE5B3yohD1lFwg',
               'player2_id': 'rec27ivyllAqIIQM5',
               'player1_coords': ('35.894364', '-78.652319'),
               'player2_coords': ('35.795349', '-78.629617'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court C',
               'morning': {'Saturday 8/26'},
               'afternoon': {'Saturday 8/26'},
               'evening': {'Tuesday 8/22'}},
              {'team_id': 'recfGdhuwFTDk5lvo',
               'player1_id': 'rec2ROHwpac9qgLDb',
               'player2_id': 'recQFqEhcmrAt40LJ',
               'player1_coords': ('33.738841', '-84.356402'),
               'player2_coords': ('33.7483254', '-84.3810483'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21'}},
              {'team_id': 'recfYDAqboXu3WEp6',
               'player1_id': 'rec6yBQjwQg1oykMz',
               'player2_id': 'recVDUIVLate23AAp',
               'player1_coords': ('35.843619', '-78.648553'),
               'player2_coords': ('35.976619', '-78.59604'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court B',
               'morning': {'Friday 8/25', 'Thursday 8/24'},
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recg1Y0bbs19w9Iu5',
               'player1_id': 'recSJZom5wFViHugI',
               'player2_id': 'rec3jbobjaGLMPJFQ',
               'player1_coords': ('35.9229', '-78.762455'),
               'player2_coords': ('35.812204', '-78.635699'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court C',
               'morning': {'Monday 8/21', 'Wednesday 8/23'},
               'afternoon': set(),
               'evening': {'Monday 8/21'}},
              {'team_id': 'recizd8ncp8ODHhNw',
               'player1_id': 'recuESDefH8j2FSoo',
               'player2_id': 'recyzR9FJR8j4TPmB',
               'player1_coords': ('35.842501', '-78.629873'),
               'player2_coords': ('35.975639', '-78.46422'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21', 'Wednesday 8/23'}},
              {'team_id': 'reclQJhRnfRTQL27z',
               'player1_id': 'recTHY5mZKxPmuFLT',
               'player2_id': 'recXqUD1O2Jfkj2gk',
               'player1_coords': ('35.785201', '-78.710355'),
               'player2_coords': ('35.785201', '-78.710355'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court C',
               'morning': {'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25', 'Monday 8/21', 'Tuesday 8/22', 'Wednesday 8/23'}},
              {'team_id': 'recle7G1RE2ShOWW2',
               'player1_id': 'recJVaugcnGDmgTgz',
               'player2_id': 'rechzxuYK4o0jqzr8',
               'player1_coords': ('35.7851988', '-78.6477971'),
               'player2_coords': ('35.880885', '-78.566288'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': {'Monday 8/21'},
               'afternoon': {'Monday 8/21'},
               'evening': {'Friday 8/25',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'reclyFy5dgLEG2KFf',
               'player1_id': 'recCYmSrmyRheehtD',
               'player2_id': 'recz3VTtkQC0GYfLh',
               'player1_coords': ('33.788674', '-84.367988'),
               'player2_coords': ('33.721128', '-84.343274'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Friday 8/25', 'Thursday 8/24', 'Wednesday 8/23'},
               'afternoon': {'Friday 8/25',
                             'Sunday 8/27',
                             'Thursday 8/24',
                             'Wednesday 8/23'},
               'evening': {'Thursday 8/24', 'Tuesday 8/22', 'Wednesday 8/23'}},
              {'team_id': 'recm20nQM2WJgJj6K',
               'player1_id': 'rec7W2vDuq27cTfyK',
               'player2_id': 'recgY0YYl5tD8zlh1',
               'player1_coords': ('35.915564', '-78.530326'),
               'player2_coords': ('35.915564', '-78.530326'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Sunday 8/27'},
               'afternoon': {'Sunday 8/27'},
               'evening': {'Monday 8/21',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Wednesday 8/23'}},
              {'team_id': 'recmzv0fqCSdNLwZn',
               'player1_id': 'recTpJl8HaAK7o2q3',
               'player2_id': 'recY9NdSEFsykCaRw',
               'player1_coords': ('35.929278', '-78.561825'),
               'player2_coords': ('35.929278', '-78.561825'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Sunday 8/27'},
               'afternoon': {'Sunday 8/27'},
               'evening': {'Monday 8/21',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Wednesday 8/23'}},
              {'team_id': 'recnGZWgDUN5FiXcR',
               'player1_id': 'rec652ayIL9JE2lns',
               'player2_id': 'recmWvWB0d093f8M8',
               'player1_coords': ('35.812493', '-78.631822'),
               'player2_coords': ('35.843572', '-78.617667'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25',
                           'Monday 8/21',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'recng7hs0S8Irlcl3',
               'player1_id': 'recAhtMuPs76jBkTv',
               'player2_id': 'rec14v1u5JbZ2f0lp',
               'player1_coords': ('35.876994', '-78.738009'),
               'player2_coords': ('35.809633', '-78.627504'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recoOAGkfTay7h4hh',
               'player1_id': 'reci5Ry8gYFyVYiX1',
               'player2_id': 'recmBIr9CBTHuS78o',
               'player1_coords': ('35.905721', '-78.662533'),
               'player2_coords': ('35.792266', '-78.626189'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': set()},
              {'team_id': 'recpUsupv90nJGvlQ',
               'player1_id': 'recFqT1yYRWXHqT9z',
               'player2_id': 'recnw8Ju4JDLqTs7K',
               'player1_coords': ('33.7455084', '-84.2986939'),
               'player2_coords': ('33.882299', '-84.340164'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Monday 8/21'}},
              {'team_id': 'recqaMa7sIyi0TnqW',
               'player1_id': 'recSNxOS6eccnOXUK',
               'player2_id': 'recjKEngMKzT9LOC8',
               'player1_coords': ('35.831859', '-78.81386'),
               'player2_coords': ('35.928286', '-78.825074'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Thursday 8/24', 'Wednesday 8/23'}},
              {'team_id': 'recqx5XXsLQKcxYhk',
               'player1_id': 'rec8qCJ9fkshng1TN',
               'player2_id': 'recI8LPzpuTrZgsYC',
               'player1_coords': ('35.763831', '-78.428095'),
               'player2_coords': ('35.765064', '-78.427028'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Sunday 8/27', 'Wednesday 8/23'}},
              {'team_id': 'recrXyt1k6hL3fvUl',
               'player1_id': 'recd3yIQAuLmdXq5p',
               'player2_id': 'recsMfvnkOt4zmjwI',
               'player1_coords': ('35.930972', '-78.454525'),
               'player2_coords': ('35.804796', '-78.680168'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court B',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Thursday 8/24', 'Tuesday 8/22'}},
              {'team_id': 'recrffewS5hZJrVkh',
               'player1_id': 'recIXvLUKkBxpE3Fq',
               'player2_id': 'recongPYmOtf0tChL',
               'player1_coords': ('35.87931', '-78.705224'),
               'player2_coords': ('35.872287', '-78.721384'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': set(),
               'afternoon': set(),
               'evening': {'Thursday 8/24', 'Tuesday 8/22'}},
              {'team_id': 'recs082k7fHjfwLt6',
               'player1_id': 'rec5XDufyFQtfhQQu',
               'player2_id': 'recIQA75MAt86s8ah',
               'player1_coords': ('33.761231', '-84.382286'),
               'player2_coords': ('33.7748402', '-84.442846'),
               'city': 'New York',
               'division': 'Beginner',
               'Home Court': 'Court B',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': {'Saturday 8/26', 'Sunday 8/27'},
               'evening': {'Friday 8/25',
                           'Monday 8/21',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'rectCdXTT3tXNsCnk',
               'player1_id': 'recCFIyDwOBrViNXp',
               'player2_id': 'recGsXRd9BMWnKD8v',
               'player1_coords': ('35.870472', '-78.686658'),
               'player2_coords': ('35.8296974', '-78.674653'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Friday 8/25',
                           'Monday 8/21',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'},
               'afternoon': {'Monday 8/21',
                             'Thursday 8/24',
                             'Tuesday 8/22',
                             'Wednesday 8/23'},
               'evening': {'Monday 8/21',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'rectcMRXJRnbY6lPE',
               'player1_id': 'recBanIn2vREKV8vF',
               'player2_id': 'recOozwZf8y9ay6ai',
               'player1_coords': ('33.854628', '-84.357769'),
               'player2_coords': ('33.881265', '-84.518554'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': {'Friday 8/25',
                           'Monday 8/21',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'},
               'afternoon': {'Monday 8/21',
                             'Thursday 8/24',
                             'Tuesday 8/22',
                             'Wednesday 8/23'},
               'evening': {'Monday 8/21',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'recw4oxXH9Rt71f0F',
               'player1_id': 'rec4OcD8W2Mk9qMbA',
               'player2_id': 'recG1yynZJbJKqrfZ',
               'player1_coords': ('35.811242', '-78.636871'),
               'player2_coords': ('35.674185', '-78.666783'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court B',
               'morning': {'Saturday 8/26'},
               'afternoon': {'Friday 8/25', 'Thursday 8/24', 'Tuesday 8/22'},
               'evening': {'Thursday 8/24', 'Tuesday 8/22'}},
              {'team_id': 'recwD55RWhKmjYqyA',
               'player1_id': 'recCKJWrmnCz0h9lT',
               'player2_id': 'recy5QZ2BYt5662SA',
               'player1_coords': ('35.78041', '-78.639094'),
               'player2_coords': ('35.773568', '-78.638937'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court B',
               'morning': set(),
               'afternoon': {'Sunday 8/27'},
               'evening': {'Saturday 8/26',
                           'Sunday 8/27',
                           'Tuesday 8/22',
                           'Wednesday 8/23'}},
              {'team_id': 'recxppOex8IYopqhw',
               'player1_id': 'recejsGJx89Y1oWYl',
               'player2_id': 'recgQH9d0PV3JVXWm',
               'player1_coords': ('35.791322', '-78.629346'),
               'player2_coords': ('35.9407387', '-78.6835407'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court C',
               'morning': {'Sunday 8/27'},
               'afternoon': {'Sunday 8/27'},
               'evening': {'Sunday 8/27'}},
              {'team_id': 'recyJKQQpNjOsIgmS',
               'player1_id': 'recjiOvHrWmIiBgv6',
               'player2_id': 'recWnCOAv4ZqwBFlQ',
               'player1_coords': ('35.783027', '-78.733121'),
               'player2_coords': ('35.808514', '-78.837623'),
               'city': 'New York',
               'division': 'Advanced',
               'Home Court': 'Court A',
               'morning': set(),
               'afternoon': {'Sunday 8/27'},
               'evening': {'Sunday 8/27'}},
              {'team_id': 'recz75zIeh1lazMCW',
               'player1_id': 'recWx3irz2j5VdKiI',
               'player2_id': 'recZgIJ20RBa8Jq7M',
               'player1_coords': ('33.590389', '-84.491979'),
               'player2_coords': ('33.636972', '-84.482617'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court C',
               'morning': set(),
               'afternoon': {'Sunday 8/27'},
               'evening': {'Sunday 8/27'}},
              {'team_id': 'recz7GwglbHR9t0C7',
               'player1_id': 'recFIqNHF6870gdb8',
               'player2_id': 'recCQVuHwz9Kk4ckh',
               'player1_coords': ('33.7379095', '-84.3776734'),
               'player2_coords': ('33.77461', '-84.397373'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court B',
               'morning': {'Friday 8/25',
                           'Monday 8/21',
                           'Saturday 8/26',
                           'Sunday 8/27',
                           'Thursday 8/24',
                           'Tuesday 8/22',
                           'Wednesday 8/23'},
               'afternoon': {'Monday 8/21', 'Wednesday 8/23'},
               'evening': {'Monday 8/21', 'Wednesday 8/23'}},
              {'team_id': 'recz9oYwr7FVC4B4u',
               'player1_id': 'rec2tzrTbFpZRD9Is',
               'player2_id': 'rec3OVlsMoX9D1Uql',
               'player1_coords': ('35.777187', '-78.691369'),
               'player2_coords': ('35.778766', '-78.685631'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26'},
               'afternoon': set(),
               'evening': {'Monday 8/21', 'Saturday 8/26', 'Sunday 8/27', 'Thursday 8/24'}}]

"""
{'team_id': 'rec0PkRLRqX17ERGT',
               'player1_id': 'recd1EtfW4z1abmmZ',
               'player2_id': 'recfwFg1Bb6fOSjEf',
               'player1_coords': ('35.715806', '-78.711512'),
               'player2_coords': ('35.582594', '-78.750939'),
               'city': 'New York',
               'division': 'Intermediate',
               'Home Court': 'Court A',
               'morning': {'Saturday 8/26', 'Sunday 8/27'},
               'afternoon': set(),
               'evening': {'Saturday 8/26'}}
"""


def get_division(data):
    data_division = data['division'].lower()
    if Division.BEGINNER.name.lower() == data_division:
        return Division.BEGINNER
    if Division.INTERMEDIATE.name.lower() == data_division:
        return Division.INTERMEDIATE
    if Division.ADVANCED.name.lower() == data_division:
        return Division.ADVANCED
    return None


def create_dates(date_texts: Set[str]):
    today = datetime.date.today()
    dates = set()
    for date_text in date_texts:
        date_values_text = date_text.split(' ')[1]
        date_value_texts = date_values_text.split('/')
        day = int(date_value_texts[1])
        month = int(date_value_texts[0])
        created_date = datetime.date(month=month, day=day, year=today.year)
        dates.add(created_date)
    return dates


def create_availability(data):
    morning_dates = create_dates(data['morning'])
    afternoon_dates = create_dates(data['afternoon'])
    evening_dates = create_dates(data['evening'])
    return Availability(morning_dates, afternoon_dates, evening_dates)


def create_teams():
    teams = set()
    for data in input_data:
        player_1 = Player(data['player1_id'], data['player1_coords'])
        player_2 = Player(data['player2_id'], data['player2_coords'])
        city = City(data['city'])
        division = get_division(data)
        home_court = Court(data['Home Court'])
        availability = create_availability(data)
        team = Team(data['team_id'], city, home_court, division, [player_1, player_2], list(), availability)
        teams.add(team)
    return teams


def main():
    teams = create_teams()
    matchmaking = MatchmakingImpl()
    result = matchmaking.create_matchups(teams)
    matchmaking.save_result(result)
    print(result)

if __name__ == '__main__':
    main()
